### ISSUE TITLE
wrong target ?

### ISSUE THREAD

**Issue by ghost** [muimota/miniminer#3]
Hi, just been playing around with your code to test a few things out, and noticed that the script produces a target of, 000000000000122cbc0000000000000000000000000000000000000000000000

then when i look on other websites its saying it should be of this length 
000000000000000000122cbc0000000000000000000000000000000000000000 

(ref: https://learnmeabitcoin.com/guide/target )

am i missing something & getting confused? or is the script throwing off a wrong target.

Thanks

**Comment by ghost** [comment]
Also another thing, on line 85, should it not be sock.sendall(b'payload') instead of     sock.sendall(payload) ????

**Comment by ghost** [comment]
any help ?

**Comment by muimota** [comment]
Hi!
 You are right, now is fixed. Te problem was the documentation I used was incorrect and didn't remove the first three bytes.

Thanks for pointing it out

**Comment by muimota** [comment]
Hi lechi, thanks for writing, right now I am pretty busy.
I think the error is in the reference, commented in the code (stack
overflow link)  the minimum difficulty, maximum target is wrong.

You can do a pull request if you have the solution

Thank you for checking and pointing the error.
